terrace/config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root 'welcome#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

terrace/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

terrace/app/models/booking.rb
class Booking < ApplicationRecord
end

terrace/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

terrace/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  # GET /bookings or /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:event_name, :wait_staff, :host, :event_type, :start_time, :end_time, :occupants, :menu_items, :room_layout, :seating, :employee_start_time, :employee_end_time, :event_phases)
    end
end

terrace/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

terrace/app/helpers/application_helper.rb
module ApplicationHelper
end

terrace/app/helpers/bookings_helper.rb
module BookingsHelper
end

terrace/app/helpers/welcome_helper.rb
module WelcomeHelper
end

terrace/app/views/bookings/_form.html.erb
<%= form_for(booking) do |f| %>
  <% if booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_name %>
    <%= f.text_field :event_name %>
  </div>

  <div class="field">
    <%= f.label :wait_staff %>
    <%= f.text_area :wait_staff %>
  </div>

  <div class="field">
    <%= f.label :host %>
    <%= f.text_area :host %>
  </div>

  <div class="field">
    <%= f.label :event_type %>
    <%= f.text_field :event_type %>
  </div>

  <div class="field">
    <%= f.label :start_time %>
    <%= f.text_field :start_time %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.text_field :end_time %>
  </div>

  <div class="field">
    <%= f.label :occupants %>
    <%= f.text_field :occupants %>
  </div>

  <div class="field">
    <%= f.label :menu_items %>
    <%= f.text_area :menu_items %>
  </div>

  <div class="field">
    <%= f.label :room_layout %>
    <%= f.text_field :room_layout %>
  </div>

  <div class="field">
    <%= f.label :seating %>
    <%= f.text_field :seating %>
  </div>

  <div class="field">
    <%= f.label :employee_start_time %>
    <%= f.text_field :employee_start_time %>
  </div>

  <div class="field">
    <%= f.label :employee_end_time %>
    <%= f.text_field :employee_end_time %>
  </div>

  <div class="field">
    <%= f.label :event_phases %>
    <%= f.text_area :event_phases %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

terrace/app/views/bookings/edit.html.erb
<h1>Editing Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

terrace/app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bookings</h1>

<table>
  <thead>
    <tr>
      <th>Event name</th>
      <th>Wait staff</th>
      <th>Host</th>
      <th>Event type</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Occupants</th>
      <th>Menu items</th>
      <th>Room layout</th>
      <th>Seating</th>
      <th>Employee start time</th>
      <th>Employee end time</th>
      <th>Event phases</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.event_name %></td>
        <td><%= booking.wait_staff %></td>
        <td><%= booking.host %></td>
        <td><%= booking.event_type %></td>
        <td><%= booking.start_time %></td>
        <td><%= booking.end_time %></td>
        <td><%= booking.occupants %></td>
        <td><%= booking.menu_items %></td>
        <td><%= booking.room_layout %></td>
        <td><%= booking.seating %></td>
        <td><%= booking.employee_start_time %></td>
        <td><%= booking.employee_end_time %></td>
        <td><%= booking.event_phases %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Booking', new_booking_path %>

terrace/app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

terrace/app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event name:</strong>
  <%= @booking.event_name %>
</p>

<p>
  <strong>Wait staff:</strong>
  <%= @booking.wait_staff %>
</p>

<p>
  <strong>Host:</strong>
  <%= @booking.host %>
</p>

<p>
  <strong>Event type:</strong>
  <%= @booking.event_type %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @booking.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @booking.end_time %>
</p>

<p>
  <strong>Occupants:</strong>
  <%= @booking.occupants %>
</p>

<p>
  <strong>Menu items:</strong>
  <%= @booking.menu_items %>
</p>

<p>
  <strong>Room layout:</strong>
  <%= @booking.room_layout %>
</p>

<p>
  <strong>Seating:</strong>
  <%= @booking.seating %>
</p>

<p>
  <strong>Employee start time:</strong>
  <%= @booking.employee_start_time %>
</p>

<p>
  <strong>Employee end time:</strong>
  <%= @booking.employee_end_time %>
</p>

<p>
  <strong>Event phases:</strong>
  <%= @booking.event_phases %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

terrace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Terrace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

terrace/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>